# reporting/params.yaml
openapi: 3.0.0
info:
  title: Reporting request parameters
  version: 1.0.0
paths: {}
components:
  schemas:
    ReportDate:
      type: string
      format: date
      example: '2014-11-24'
    ReportStatus:
      type: array
      items:
        type: string
        enum:
          - 'ACTIVE'
          - 'PAUSED'
          - 'BUDGET_REACHED'
          - 'DAILY_BUDGET_REACHED'
          - 'DELETED'
          - 'DELETED_BY_CS'
          - 'SUSPENDED_BY_CS'
          - 'DOMAIN_PENDING'
      default: [ 'ACTIVE' ]
      example: [ 'ACTIVE', 'PAUSED' ]
    AdIDs:
      type: array
      items:
        type: integer
        format: int64
      example: [ 1,2,3 ]
    ReportTimeAggregation:
      type: string
      required: false
      description: 'Granularity of the timeseries breakdown.'
      enum:
        - 'daily'
        - 'weekly'
        - 'monthly'
        - 'yearly'
      default: 'daily'
    ReportAdsFields:
      description: 'Comma-separated list of column fields to include in the report. Possible values are the response model fields. By default all fields are included, and this may affect the speed of data generation.'
      type: array
      enum:
        - 'date'
        - 'adID'
        - 'L1Category'
        - 'L2Category'
        - 'L3Category'
        - 'title'
        - 'startDate'
        - 'endDate'
        - 'bidMicros'
        - 'spentMicros'
        - 'clicks'
        - 'impressions'
        - 'viewCTR'
        - 'websiteClicks'
        - 'emails'
        - 'engagementCTR'
        - 'region'
        - 'vendorID'
        - 'externalURL'
