# reporting/requests.yaml
openapi: 3.0.0
info:
  title: Reporting request component schemas
  version: 1.0.0
paths: {}
components:
  schemas:
    MetricsDataRequestV2:
      required:
        - timeRanges
        - metrics
      type: object
      properties:
        timeRanges:
          description: 'This field is used to specify one ore more distinct time periods to fetch data for, across which all other query parameters will be the same. Supplying a single range is sufficient for most needs, but the flexibility is provided to ask for multiple at the same time'
          type: array
          items:
            type: object
            required:
              - period
            properties:
              period:
                description: 'There are several predefined period values at your disposal: ``today``, ``yesterday``, ``thisWeek``, ``lastWeek``, ``thisMonth``, ``lastMonth``, ``thisYear``, and ``lastYear``, with their obvious meanings. A week runs from Monday to Sunday. If you use a predefined period for a particular time range, the from and to fields of that time range will be ignored.
                <br>
                To use a ``custom`` period, you need to provide the start (from) and end (to) date (both inclusive, tenant timezone assumed) in the following format: ``YYYY-MM-DD``. The end date cannot be before the start one. '
                type: string
                enum:
                  - 'today'
                  - 'yesterda'
                  - 'thisWeek'
                  - 'lastWeek'
                  - 'thisMonth'
                  - 'lastMonth'
                  - 'thisYear'
                  - 'lastYear'
                  - 'custom'
              from:
                description: 'A start date (inclusive) for the custom period for which performance metrics are requested.'
                type: string
                format: date
              to:
                description: 'An end date (inclusive) for the custom period for which performance metrics are requested.'
                type: string
                format: date
        aggregate:
          description: 'Used in combination with the ``am:date`` dimension, it specifies the granularity/resolution of the time according to which the metrics data will be grouped in buckets.'
          type: string
          enum:
            - 'daily'
            - 'weekly'
            - 'quarterly'
            - 'monthly'
            - 'yearly'
        dimensions:
          type: array
          items:
            type: string
            description: 'A dimension is an attribute of each performance event, and is used for grouping your data. For example, the dimension `Country` indicates where a click originated from. The `Date` dimension indicates the date when a particular ad was viewed or clicked. It is also possible to make a report without dimensions; in this case, the total result is calculated.
            <br>
            <span>&#9888;</span><br>
            Date is a special dimension, in that you can specify the granularity of the timeseries breakdown. In other words, data is aggregated over units of time (such as days, weeks, months or years) when calculating metrics over it.
            '
            enum:
              - 'am:date'
              - 'am:adID'
              - 'am:categoryID'
              - 'am:regionID'
              - 'am:campaignID'
        metrics:
          type: array
          items:
            type: string
            description: 'Metrics are numeric values based on quantitative aggregations over dimensions’ values; every query requires at least one metric field to be requested. For example, the metric `Clicks` indicates the total number of clicks, while `ViewCTR` indicates the click-through rate for ads.'
            enum:
              - 'am:clicks'
              - 'am:impressions'
              - 'am:websiteClicks'
              - 'am:emails'
              - 'am:engagements'
              - 'am:viewCTR'
              - 'am:websiteCTR'
              - 'am:spentMicros'
              - 'am:engagementCTR'
              - 'am:avgBidMicros'
              - 'am::avgSpentMicros'
              - 'am:eSpentMicros'
              - 'am:sessionESpentMicros'
              - 'am:sessionsWithClicks'
              - 'am:sessionsWithImpressions'
              - 'am:sessionsWithWebsiteClicks'
              - 'am:sessionsWithEmails'
              - 'am:sessionsWithEngagements'
              - 'am:sessionViewCTR'
              - 'am:sessionWebsiteCTR'
              - 'am:sessionEngagementCTR'
        sorts:
          type: array
          description: 'To sort the resulting data, use the sorts top-level query field. Sorts is an array of sort clauses.'
          items:
            type: object
            properties:
              field:
                description: 'Either a valid metric or a valid dimension. It is only permitted to sort on the fields that are requested.'
                type: string
              direction:
                description: 'The sorting direction for the requested field.'
                type: string
                enum:
                  - 'asc'
                  - 'desc'
          example:
            - field: am:date
              direction: desc
            - field: am:adID
              direction: asc
        filters:
          description: 'Used to request a subset of data based on certain conditions. 
          For example, you can filter on particular category, region, or ad ID. Filters can currently be used on any of the supported dimensions (except for ``am:date``).
          In the request query, they should be provided as an array of filter clauses which filters out the requested data on particular field values.
          <br><br>
          Each filter in the list adds more restriction on the result, i.e., there is implicit AND operation between them. The only valid operator at the moment is the set operator in, and requires an array of values to be passed in the value field of the filter.
          '
          type: array
          items:
            type: object
            properties:
              field:
                description: 'The dimension field on whihc a filter is applied.'
                type: string
                enum:
                  - 'am:date'
                  - 'am:adID'
                  - 'am:categoryID'
                  - 'am:regionID'
                  - 'am:campaignID'
              operator:
                description: 'The only valid operator at the moment is ``in``.'
                type: string
                enum:
                  - 'in'
              value:
                description: 'The value(s) of the corresponding dimension field on which to filter.'
                type: array
                items:
                  type: number
                  format: double
          example:
            - field: am:adID
              operator: in
              value:
                - 1111
                - 2222
                - 3333
            - field: am:regionID
              operator: in
              value:
                - 1234
                - 5678
        enrichment:
          type: array
          items:
            description: 'It is possible to enrich the reports with “handy” ad-related data for which only the present-moment values are available, 
            such as the ad title, or category description. Requesting these fields makes sense only if ``am:adID`` is in the requested dimensions.'
            type: string
            enum:
              - 'am:currentAdTitle'
              - 'am:currentAdStartDate'
              - 'am:currentAdEndDate'
              - 'am:currentAdBidMicros'
              - 'am:currentAdCategoryL1'
              - 'am:currentAdCategoryL2'
              - 'am:currentAdCategoryL3'
              - 'am:currentAdImage'
              - 'am:currentAdVendorID'
              - 'am:currentAdRegion'
              - 'am:currentAdExternalID'
              - 'am:currentAdExternalURL'
        limit:
          description: 'Depending on the amount and shape of the requested data, it is worthwhile to paginate the results, for efficiency.
          This field limits of elements in the response, per time range.'
          type: number
          example: 100
        offset:
          description: 'Depending on the amount and shape of the requested data, it is worthwhile to paginate the results, for efficiency.
          This field is the index of the first row of the requested data (per time range).'
          type: number
          default: 0
        searchPhrase:
          description: 'String to match against an ad title.'
          type: string
          example: 'bike'