# campaigns/params.yaml
openapi: 3.0.0
info:
  title: Campaign request parameters
  version: 1.0.0
paths: {}
components:
  parameters:
    StatusV5:
      name: status
      in: path
      required: true
      description: 'Each campaign can be set in one of a predefined set of user-controlled states.'
      schema:
        enum:
          - 'ACTIVE'
          - 'PAUSED'
        example: 'PAUSED'
