# campaigns/params.yaml
openapi: 3.0.0
info:
  title: Campaign request parameters
  version: 1.0.0
paths: {}
components:
  parameters:
    StatusV5:
      name: status
      in: path
      required: true
      description: 'Each campaign can be set in one of a predefined set of user-controlled states.'
      schema:
        enum:
          - 'ACTIVE'
          - 'PAUSED'
        example: 'PAUSED'
    ScheduledResumeDate:
      name: scheduledResumeDate
      in: query
      description: 'The date at which the paused campaign should be automatically resumed (activated) by the system. 
           It must be between one calendar day and 365 calendar days in the future (in local tenant timezone). 
           This field will be cleared the moment the campaign is activated, either automatically or manually.'
      schema:
        type: string
        format: date
        example: '2025-12-31'

