# feeds/params.yaml
openapi: 3.0.0
info:
  title: Feed request parameters
  version: 1.0.0
paths: {}
components:
  parameters:
    ImportID:
      name: id
      in: path
      required: true
      schema:
        type: number
        example: 123
    Format:
      name: format
      in: query
      schema:
        enum:
          - tsv
          - xml
        example: tsv
        default: xml
